// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xicddpjqiywrnukfaabs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpY2RkcGpxaXl3cm51a2ZhYWJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NzczODgsImV4cCI6MjA3NDA1MzM4OH0.DUuMX7nT-932qg71Vxx25fvdBtXsOrrHsND9c20V2Y0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});